create table admin (
        id number generated by default as identity,
        email varchar2(255) unique not null,
        password varchar2(255) not null,
        primary key (id)
);

create table provenance (
	id number generated by default as identity,
	name varchar(255) not null,	
	id_admin number not null,
	foreign key(id_admin) references admin(id),
	primary key(id)
);

create table categorie (
	id number generated by default as identity,
	name varchar2(255) not null,
	id_admin number not null,
	primary key (id),
	foreign key(id_admin) references admin(id)
);

create table produit(
    id number generated by default as identity,
	name varchar(255) not null,
	description clob not null,
	image varchar(255),
	id_provenance integer not null,
	id_categorie integer not null,
	id_admin number not null,
	primary key(id),
	foreign key(id_admin) references admin(id),
	foreign key(id_provenance) references provenance(id),
	foreign key(id_categorie) references categorie(id)
);
