create table admin
(
    id       number generated by default as identity,
    email    varchar2(255) unique not null,
    password varchar2(255) not null,
    primary key (id)
);

create table categorie
(
    id       number generated by default as identity,
    name     varchar2(255) not null,
    id_admin number not null,
    primary key (id),
    foreign key (id_admin) references admin (id)
);

create table produit
(
    id               number generated by default as identity,
    name             varchar(255) not null,
    description      clob         not null,
    image            varchar(255),
    id_categorie     integer      not null,
    date_publication date default SYSDATE,
    id_admin         number       not null,
    primary key (id),
    foreign key (id_admin) references admin (id),
    foreign key (id_categorie) references categorie (id)
);

create table evolution
(
    id         number generated by default as identity,
    date       date default now(),
    prix       varchar(15) not null,
    id_produit integer     not null,
    primary key (id),
    foreign key (id_produit) references produit (id)
);

insert into admin(email, password) values('24nomeniavo@gmail.com', '24joeJoe');

insert into categorie(name, id_admin) values('Farming', 1);
insert into categorie(name, id_admin) values('Artisanal', 1);
insert into categorie(name, id_admin) values('Breeding', 1);
insert into categorie(name, id_admin) values('Fishing', 1);
