create table admin
(
    id       number generated by default as identity,
    email    varchar2(255) unique not null,
    password varchar2(255) not null,
    primary key (id)
);
-- for sqlite
create table admin
(
    id       integer primary key autoincrement not null,
    email    varchar2(255) unique not null,
    password varchar2(255) not null,
);

create table categorie
(
    id       integer primary key autoincrement not null,
    name     varchar2(255) not null,
    id_admin integer not null,
    foreign key (id_admin) references admin (id)
);

create table produit
(
    id               integer primary key autoincrement not null,
    name             varchar(255) not null,
    description      clob         not null,
    image            varchar(255),
    id_categorie     integer      not null,
    date_publication date default (date('now')),
    id_admin         integer       not null,
    foreign key (id_admin) references admin (id),
    foreign key (id_categorie) references categorie (id)
);

insert into admin(email, password)
values ('24nomeniavo@gmail.com', '24joeJoe');

insert into categorie(name, id_admin)
values ('Farming', 1);
insert into categorie(name, id_admin)
values ('Artisanal', 1);
insert into categorie(name, id_admin)
values ('Breeding', 1);
insert into categorie(name, id_admin)
values ('Fishing', 1);
